"""create labels table

Revision ID: ce5461180e47
Revises: 
Create Date: 2026-10-02 14:33:32.540235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5461180e47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labels_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_labels_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labels_name'))
        batch_op.drop_index(batch_op.f('ix_labels_id'))

    op.drop_table('labels')
    # ### end Alembic commands ###
